#!/bin/bash

echo ""

# Check License Manager

RESULT=`ps -ef | grep " synd" | grep -v grep`
if [[ -n "$RESULT" ]]
then
  echo "License Manager: OK"
else
  echo "License Manager: NOT RUNNING!"
fi

# Check xfServer

RESULT=`ps -ef | grep "rsynd -p 2330" | grep -v grep`

if [[ -n "$RESULT" ]]
then
  echo "xfServer:        OK"
else
  echo "xfServer:        NOT RUNNING!"
fi

# Check xfServerPlus

RESULT=`ps -ef | grep "rsynd -w -p 2356" | grep -v grep`

if [[ -n "$RESULT" ]]
then
  echo "xfServerPlus:    OK"
else
  echo "xfServerPlus:    NOT RUNNING!"
fi

echo ""

