#!/bin/bash
#
#------------------------------------
# Start the Synergy/DE License Server
#------------------------------------
source /synergy/ConfigureSynergy

gateway_address=$(/sbin/ip route | awk '/default/ { print $3 }')
lmu -nf $gateway_address

synd

