#!/bin/bash

source /synergy/ConfigureSynergy

RESULT=`ps -ef | grep "rsynd -w -p 2356" | grep -v grep`

if [[ -z "$RESULT" ]]
then
  if [[ "$1" != "quiet" ]]
  then
    echo "Starting xfServerPlus on port 2356"
    rsynd -w -p 2356 -u $USER
  else
    rsynd -w -p 2356 -u $USER > /dev/null
  fi
else
  if [[ "$1" != "quiet" ]]; then echo "xfServerPlus is already running on port 2356"; fi
fi

RESULT=`ps -ef | grep "rsynd -w -p 2357" | grep -v grep`

if [[ -z "$RESULT" ]]
then
  if [[ "$1" != "quiet" ]]
  then
    echo "Starting xfServerPlus on port 2357"
    rsynd -w -p 2357 -u $USER -rd 4444:30
  else
    rsynd -w -p 2357 -u $USER -rd 4444:30 > /dev/null
  fi
else
  if [[ "$1" != "quiet" ]]; then echo "xfServerPlus is already running on port 2357"; fi
fi

